<a href="https://colab.research.google.com/github/augustoogui/Analise-de-Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

#Series

In [6]:
idades = pd.Series([15,52,30,26])
idades

0    15
1    52
2    30
3    26
dtype: int64

In [7]:
idades[2]

np.int64(30)

In [8]:
idades.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
idades.values

array([15, 52, 30, 26])

In [10]:
idades.abs

<bound method NDFrame.abs of 0    15
1    52
2    30
3    26
dtype: int64>

In [11]:
idades.flags

#DataFrame

In [12]:
import numpy as np

In [14]:
df = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]), columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
dados = {'valor1': [1,2], 'valor2': [3,4], 'valor3':[5,6]}
df2 = pd.DataFrame(data=dados)
df2

   valor1  valor2  valor3
0       1       3       5
1       2       4       6

In [19]:
dados = {'valor1': [1,2], 'valor2': [3,4], 'valor3':[5,6]}
df3 = pd.DataFrame(data=dados, index = ['a', 'b'])
df3

   valor1  valor2  valor3
a       1       3       5
b       2       4       6

In [20]:
df3.values

array([[1, 3, 5],
       [2, 4, 6]])

In [21]:
df3.index

Index(['a', 'b'], dtype='object')

In [22]:
df3.columns

Index(['valor1', 'valor2', 'valor3'], dtype='object')

# Leitura de Arquivos

In [10]:
import pandas as pd
df = pd.read_excel("/content/personagens_quadrinhos.xlsx", sheet_name="DC Comics")
df

          Personagem  Ano de Criação
0           Superman            1938
1             Batman            1939
2   Mulher-Maravilha            1941
3              Flash            1940
4     Lanterna Verde            1940
5            Aquaman            1941
6            Coringa            1940
7        Mulher-Gato            1940
8              Robin            1940
9           Ciborgue            1980
10            Shazam            1939

In [11]:
df = pd.read_excel("/content/personagens_quadrinhos.xlsx", sheet_name="Marvel")
df

         Personagem  Ano de Criação
0      Homem-Aranha            1962
1    Homem de Ferro            1963
2   Capitão América            1941
3              Hulk            1962
4         Wolverine            1974
5              Thor            1962
6          Deadpool            1991
7     Pantera Negra            1966
8   Doutor Estranho            1963
9        Tempestade            1975
10          Ciclope            1963

In [12]:
df.head()

        Personagem  Ano de Criação
0     Homem-Aranha            1962
1   Homem de Ferro            1963
2  Capitão América            1941
3             Hulk            1962
4        Wolverine            1974

In [13]:
df[:6]

        Personagem  Ano de Criação
0     Homem-Aranha            1962
1   Homem de Ferro            1963
2  Capitão América            1941
3             Hulk            1962
4        Wolverine            1974
5             Thor            1962

In [15]:
df.sample(5)

         Personagem  Ano de Criação
9        Tempestade            1975
10          Ciclope            1963
2   Capitão América            1941
5              Thor            1962
6          Deadpool            1991

In [16]:
df.tail()

         Personagem  Ano de Criação
6          Deadpool            1991
7     Pantera Negra            1966
8   Doutor Estranho            1963
9        Tempestade            1975
10          Ciclope            1963

In [17]:
df.dtypes

Personagem        object
Ano de Criação     int64
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Personagem      11 non-null     object
 1   Ano de Criação  11 non-null     int64
dtypes: int64(1), object(1)
memory usage: 308.0+ bytes

In [23]:
df.describe(

)

       Ano de Criação
count       11.000000
mean      1965.636364
std         12.118356
min       1941.000000
25%       1962.000000
50%       1963.000000
75%       1970.000000
max       1991.000000

In [25]:
df.select_dtypes("object")

         Personagem
0      Homem-Aranha
1    Homem de Ferro
2   Capitão América
3              Hulk
4         Wolverine
5              Thor
6          Deadpool
7     Pantera Negra
8   Doutor Estranho
9        Tempestade
10          Ciclope

In [28]:
df.rename(columns={'personagem': 'ano criação'})
df

         Personagem  Ano de Criação
0      Homem-Aranha            1962
1    Homem de Ferro            1963
2   Capitão América            1941
3              Hulk            1962
4         Wolverine            1974
5              Thor            1962
6          Deadpool            1991
7     Pantera Negra            1966
8   Doutor Estranho            1963
9        Tempestade            1975
10          Ciclope            1963

# Exercícios

In [32]:
import pandas as pd
dados = {"Nome": ["Ana", "Bruno", "Carla", "Diego", "Elias"],
         "Idade": [25, 30, 45, 32, 28,],
         "Cidade":["São Paulo", "Guarulhos", "São Paulo", "Campinas", "Campinas"]
         }

df = pd.DataFrame(dados)
print(df)

    Nome  Idade     Cidade
0    Ana     25  São Paulo
1  Bruno     30  Guarulhos
2  Carla     45  São Paulo
3  Diego     32   Campinas
4  Elias     28   Campinas

# 2.

In [35]:
# selecionar apenas a coluna "Idade"
idades = df["Idade"]
print(idades)

0    25
1    30
2    45
3    32
4    28
Name: Idade, dtype: int64

In [36]:
# Selecionar linhas onde a idade é maior que 25
maiores_25 = df[df["Idade"] > 25]

print(maiores_25)

    Nome  Idade     Cidade
1  Bruno     30  Guarulhos
2  Carla     45  São Paulo
3  Diego     32   Campinas
4  Elias     28   Campinas

# 3.

In [37]:
df["Maior de idade"] = df["Idade"] > 18
print(df)

    Nome  Idade     Cidade  Maior de idade
0    Ana     25  São Paulo            True
1  Bruno     30  Guarulhos            True
2  Carla     45  São Paulo            True
3  Diego     32   Campinas            True
4  Elias     28   Campinas            True