<a href="https://colab.research.google.com/github/augustoogui/Analise-de-Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

#Series

In [6]:
idades = pd.Series([15,52,30,26])
idades

0    15
1    52
2    30
3    26
dtype: int64

In [7]:
idades[2]

np.int64(30)

In [8]:
idades.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
idades.values

array([15, 52, 30, 26])

In [10]:
idades.abs

<bound method NDFrame.abs of 0    15
1    52
2    30
3    26
dtype: int64>

In [11]:
idades.flags

#DataFrame

In [12]:
import numpy as np

In [14]:
df = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]), columns=['a', 'b', 'c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
dados = {'valor1': [1,2], 'valor2': [3,4], 'valor3':[5,6]}
df2 = pd.DataFrame(data=dados)
df2

   valor1  valor2  valor3
0       1       3       5
1       2       4       6

In [19]:
dados = {'valor1': [1,2], 'valor2': [3,4], 'valor3':[5,6]}
df3 = pd.DataFrame(data=dados, index = ['a', 'b'])
df3

   valor1  valor2  valor3
a       1       3       5
b       2       4       6

In [20]:
df3.values

array([[1, 3, 5],
       [2, 4, 6]])

In [21]:
df3.index

Index(['a', 'b'], dtype='object')

In [22]:
df3.columns

Index(['valor1', 'valor2', 'valor3'], dtype='object')

# Leitura de Arquivos

In [ ]:
df = pd.read